CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS raw_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    time DOUBLE PRECISION NOT NULL,

    v1  DOUBLE PRECISION NOT NULL,
    v2  DOUBLE PRECISION NOT NULL,
    v3  DOUBLE PRECISION NOT NULL,
    v4  DOUBLE PRECISION NOT NULL,
    v5  DOUBLE PRECISION NOT NULL,
    v6  DOUBLE PRECISION NOT NULL,
    v7  DOUBLE PRECISION NOT NULL,
    v8  DOUBLE PRECISION NOT NULL,
    v9  DOUBLE PRECISION NOT NULL,
    v10 DOUBLE PRECISION NOT NULL,
    v11 DOUBLE PRECISION NOT NULL,
    v12 DOUBLE PRECISION NOT NULL,
    v13 DOUBLE PRECISION NOT NULL,
    v14 DOUBLE PRECISION NOT NULL,
    v15 DOUBLE PRECISION NOT NULL,
    v16 DOUBLE PRECISION NOT NULL,
    v17 DOUBLE PRECISION NOT NULL,
    v18 DOUBLE PRECISION NOT NULL,
    v19 DOUBLE PRECISION NOT NULL,
    v20 DOUBLE PRECISION NOT NULL,
    v21 DOUBLE PRECISION NOT NULL,
    v22 DOUBLE PRECISION NOT NULL,
    v23 DOUBLE PRECISION NOT NULL,
    v24 DOUBLE PRECISION NOT NULL,
    v25 DOUBLE PRECISION NOT NULL,
    v26 DOUBLE PRECISION NOT NULL,
    v27 DOUBLE PRECISION NOT NULL,
    v28 DOUBLE PRECISION NOT NULL,

    amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),

    is_fraud SMALLINT NOT NULL CHECK (is_fraud IN (0,1)),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT unique_transaction_record UNIQUE (
        time,
        v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,
        v11,v12,v13,v14,v15,v16,v17,v18,v19,v20,
        v21,v22,v23,v24,v25,v26,v27,v28,
        amount,
        is_fraud
    )
);